services:
  gateway:
    environment:
      - ENVIRONMENT=STG
  surf-data-service:
    environment:
      - ENVIRONMENT=STG
  notification-service:
    environment:
      - ENVIRONMENT=STG
  scheduler-service:
    environment:
      - ENVIRONMENT=STG
      - SCHEDULE_SECONDS=300
