services:
  gateway:
    image: ${REGISTRY}/surfpulse-gateway:${APP_TAG}

  surf-data-service:
    image: ${REGISTRY}/surfpulse-surf-data-service:${APP_TAG}

  notification-service:
    image: ${REGISTRY}/surfpulse-notification-service:${APP_TAG}

  scheduler-service:
    image: ${REGISTRY}/surfpulse-scheduler-service:${APP_TAG}

  jaeger:
    image: jaegertracing/all-in-one:1.57
